### ISSUE TITLE
Example Scripts updated and Some clarification

### ISSUE THREAD

**Issue by Fortist** [Wurmcraft/WurmTweaks2#1]
I know where to find the example scripts for some of the mods, but not all of them have been added yet.
And in addition clarification on Inputs, Outputs and what some numbers mean for certain mods.

While, I get some are pretty obvious after looking over it again, some are not.

**Comment by Wurmatron** [comment]
Until i get some time to update them (which i have known for a while). You can look at my modpack ones which are updated and inuse with this mod. Checkout [https://github.com/Wurmcraft/Survival-of-the-Ages/tree/master/scripts](https://github.com/Wurmcraft/Survival-of-the-Ages/tree/master/scripts)

**Comment by Wurmatron** [comment]
Note: Support in the .2.1 is missing quite a lot of support due to how the Thaumcraft API works when i get some more time ill finish the support

**Comment by Fortist** [comment]
Good to know, gonna check it out.

**Comment by Wurmatron** [comment]
https://github.com/Wurmcraft/WurmTweaks2/tree/master/scripts
