### ISSUE TITLE
Rewrite WurmTweaks

### ISSUE THREAD

**Issue by Wurmatron** [Wurmcraft/WurmTweaks2#10]
- [x] AbyssalCraft
- [X] ActuallyAdditions
- [x] AE2
- [x] AstralSorcery
- [x] Avaritia
- [x] BetterWithMods
- [x] BloodMagic
- [x] Botania
- [X] Charcoal Pit
- [x] DraconicEvolution
- [x] Enviormental Tech
- [x] ExNihilo
- [x] ExtraUtils
- [x] Galacticraft
- [X] IE
- [x] Industrial Forgoing
- [x] Mekanism
- [X] Minecraft
- [x] NuclearCraft
- [X] OreStages
- [X] GameStages 
- [X] TAN
- [x] Pnumaticraft
- [x] TConstruct
- [x] TechReborn
- [x] Thermal Expansion

**Comment by Matthewacon** [comment]
#4, #6

**Comment by Matthewacon** [comment]
#9

**Comment by Wurmatron** [comment]
- [ ] Minecraft 
- [ ] AbyssalCraft
- [ ] GameStages
- [ ] Ore Stages
- [ ]  AE2
- [ ] Actually Adittions
- [ ] Astral Sourcery
- [ ] Avaritia
- [ ] Better With Mods
- [ ] Blood Magic
- [ ] Calculator
- [ ] Immersive Enginerring
- [ ] Industrial Forgoing
- [ ] Mekanism
- [ ] Pnumaticraft
- [ ] TConstruct
- [ ] Tech Reborn
- [ ]  Thaumcraft
- [ ] Thermal Expansion
- [ ] Tough as Nails
- [ ] Galacticraft
- [ ] IC2

**Comment by Wurmatron** [comment]
Finished, just need to confirm features
