### ISSUE TITLE
Comparison to CraftTweaker

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [Wurmcraft/WurmTweaks2#13]
What is the major differences. Like why use this over CraftTweaker

**Comment by CrankySupertoonArchive** [comment]
Found some more info. Am im correct that instead of ZenScript it uses Worm Script which is JavaScript. Also you dont add them to a configs folder you add them to a website which the mod pulls from. And doesnt it emulate the crafting table so reloading works?

**Comment by Wurmatron** [comment]
Reloading recipes mostly work but it can be glitchy sometimes depending on the mods loaded and what the scripts are doing / loading.

Note: Reloading works a lot better with v0.3.0 once that comes out due to it being multithreading and being able to do a lot more without taking forever to load
