### ISSUE TITLE
Cobblestone compressed + netherrack recipe

### ISSUE THREAD

**Issue by troykoffeman** [Wurmcraft/WurmTweaks2#16]
cobblestone compression still doesnt work fully
netherrack suggestion recipe in cauldron.
1 triple compressed cobble + 7 blocks of charcoal + 1 charcoal (64 total charcoal)

regeneration also doesnt work anymore
bloomery seems to have broken again

**Comment by Wurmatron** [comment]
Moved to https://github.com/Wurmcraft/Survival-of-the-Ages/issues/30
