### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by forestbat** [Wurmcraft/WurmTweaks2#2]
You say  “Unlike MineTweaker / CraftTweaker this system is a lot more customizable for everyone's modpack needs including the ability to use an online recipe distribution allowing the recipe updates to be active within a few minutes”，what does it mean？
We can't reload .zs files in 1.12，so does it mean that we don't need to reload .ws files and they will update automatically？
And what does “IXI BBB IXI I”，“BAB BCB BAB A” mean？

**Comment by Wurmatron** [comment]
First off the online recipe system is a way of allowing customized modpacks recipes that don't require manual syncing aka a modpack update or requiring the players to join a server to get those recipes. This is done by using some kind of file hosting service and linking it to the modpack to run those scripts when the client is started although latter I do plan on having it check for updates.  Currently, WurmTweaks can reload scripts however it may cause some glitching (for example recipes don't sync to clients unless they chose to reload there client as well)  However to use this system the 'removeAllRecipes' (Crafting, Furnace, Machines) for that type must be enabled.
`“IXI BBB IXI I” = [[<ItemI> <itemX> <itemI>] [<itemB> <itemB> <itemB>] [<ItemI> <itemX> <itemI>]]`
You threat the I or X as a varable thats linked to an item that latter within the recipe. Till i get some extra time  to create a full turotail check out my modpack using this at [https://github.com/Wurmcraft/Survival-of-the-Ages/tree/master/scripts](https://github.com/Wurmcraft/Survival-of-the-Ages/tree/master/scripts)

#1

**Comment by Wurmatron** [comment]
https://github.com/Wurmcraft/WurmTweaks2/tree/master/scripts
