### ISSUE TITLE
TechReborn machine recipes removed when "removeAllMachineRecipes" is false

### ISSUE THREAD

**Issue by zayats1** [Wurmcraft/WurmTweaks2#20]
https://i.imgur.com/ZUKzGZS.png
https://i.imgur.com/pihe8Jm.png
https://i.imgur.com/KMnRGf0.png

**Comment by zayats1** [comment]
https://i.imgur.com/KMnRGf0.png

**Comment by Wurmatron** [comment]
also 
```
scriptDir=mods\WurmTweakscripts
```
should be
```
    S:scriptDir=config\WurmTweaks
```

**Comment by Wurmatron** [comment]
Check to make sure you are using v0.3.4
 
Confirmed working with this config
http://prntscr.com/kxfd4s

**Comment by Wurmatron** [comment]
If you are still having issues with the current version feel free to report that
