### ISSUE TITLE
Crashes with Quark and Pams Loottables on World Generation.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Wurmcraft/WurmTweaks2#26]
I was testing this for you and discovered this mod does not like Pams Harvest Craft or Quark 
[crash-2019-01-26_09.30.28-server.txt](https://github.com/Wurmcraft/WurmTweaks2/files/2799265/crash-2019-01-26_09.30.28-server.txt)
[crash-2019-01-26_09.37.33-server.txt](https://github.com/Wurmcraft/WurmTweaks2/files/2799266/crash-2019-01-26_09.37.33-server.txt)
[crash-2019-01-26_09.42.25-server.txt](https://github.com/Wurmcraft/WurmTweaks2/files/2799267/crash-2019-01-26_09.42.25-server.txt)

**Comment by Wurmatron** [comment]
Change `B:removeAllLoot=true` to `B:removeAllLoot=false`

**Comment by Wurmatron** [comment]
Seems they don't play nice when they don't have any loot to work with. This setting is mainly used for WurmTweaks to remove all the default loot and add your own without having to worry about removing X loot from the loot table.
