### ISSUE TITLE
Prevent mod support classes from being loaded if it's not installed

### ISSUE THREAD

**Issue by Matthewacon** [Wurmcraft/WurmTweaks2#4]
Right now, if you load up WurmTweaks in a pack without all the supported mods, your game will crash from unresolved imports. Just prevent support classes from being loaded if they are not loaded in the pack.

**Comment by Matthewacon** [comment]
This is still a problem

**Comment by Wurmatron** [comment]
Should not crash due to new script system using only annotations

**Comment by Wurmatron** [comment]
nvm
