### ISSUE TITLE
Feature request: Ex Nihilo (Creation, Adsencio, etc.) support

### ISSUE THREAD

**Issue by Georg255** [Wurmcraft/WurmTweaks2#9]
I'd like to request support for the sieve, the barrel and the crucible, please.  This mod is a blessing to modpack makers everywhere!

**Comment by Wurmatron** [comment]
https://minecraft.curseforge.com/projects/ex-nihilo-creatio

**Comment by Wurmatron** [comment]
https://minecraft.curseforge.com/projects/ex-nihilo-adscensio

**Comment by Matthewacon** [comment]
@Georg255 we're planning on a full mod rewrite in the next week or so, which will add support for the mods that you've requested. I would hold off on any large projects that include this mod as the rewrite may change the API. That being said, if you run across any bugs throughout your usage, please don't hesitate to report them as an issue.

**Comment by Georg255** [comment]
Understood.  Thanks for the update!

**Comment by Wurmatron** [comment]
Support Disabled in 0.3.0 due to issues with imports causing a crash

**Comment by Wurmatron** [comment]
Support Readded in 0.0.3.2 once released
